openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: Local server
  url: http://localhost:8080/v1
security:
- {}
tags:
- description: not yet ready
  name: mockup
paths:
  /mockup:
    post:
      operationId: createmockup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mockup'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mockup'
          description: seccessful operation
      summary: Creates the data
      tags:
      - mockup
      x-eov-operation-handler: controllers/MockupController
  /mockup/{mockupId}:
    delete:
      operationId: deletemockup
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: mockupId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - mockup
      x-eov-operation-handler: controllers/MockupController
    get:
      operationId: getmockup
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: mockupId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mockup'
          description: seccessful operation
      summary: Get the element
      tags:
      - mockup
      x-eov-operation-handler: controllers/MockupController
    put:
      operationId: updatemockup
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: mockupId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mockup'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mockup'
          description: seccessful operation
      summary: Updates the element
      tags:
      - mockup
      x-eov-operation-handler: controllers/MockupController
  /mockup/getAll:
    get:
      operationId: getAllmockup
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/mockup'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - mockup
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/MockupController
components:
  schemas:
    mockup:
      example:
        firstname: firstname
        _id: _id
        lastname: lastname
      properties:
        _id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
      required:
      - firstname
      - lastname
      type: object
